apiVersion: azure.upbound.io/v1beta1
metadata:
  name: azure-provider
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: kube-system
      name: azure-secret
      key: creds