apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-02-09T03:53:49Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 247
  name: guestbook-argo
  namespace: argocd
  resourceVersion: "872870"
  uid: 52298874-f85b-47c1-bfe4-50827bb32f9b
spec:
  destination:
    namespace: hackathon
    server: https://target-cluster-dns-d99716bc.hcp.eastus2.azmk8s.io:443
  project: default
  source:
    path: guestbook
    repoURL: https://gitlab.com/hackathon8230906/microservices_repo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true