apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: guestbook-argo
  namespace: argocd
spec:
  destination:
    namespace: hackathon
    server: https://target-cluster-dns-d99716bc.hcp.eastus2.azmk8s.io:443
  project: default
  source:
    path: guestbook
    repoURL: https://gitlab.com/hackathon8230906/microservices_repo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true