apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmanagedclusters.compositions.io
spec:
  group: compositions.io
  names:
    kind: XManagedCluster
    plural: xmanagedclusters
  claimNames:
    kind: ManagedCluster
    plural: managedclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  version:
                    description: Supported by provider Kubernetes version
                    type: string
                  region:
                    description: Cloud region for provisioned resources
                    type: string
                    default: use1
                  nodeSize:
                    description: The node's size; supported; small, medium, large
                    type: string
                    default: small
                  nodeCount:
                    description: The desired number of nodes
                    type: integer
                    default: 1
                required:
                - version
            required:
            - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The cluster name
                type: string
              resourceGroupId:
                type: string
