apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: hackathon-2023-aks
  labels:
    crossplane.io/xrd: xmanagedclusters.compositions.io
    provider: azure
    cluster: aks
spec:
  compositeTypeRef:
    apiVersion: compositions.io/v1alpha1
    kind: XManagedCluster
  publishConnectionDetailsWithStoreConfigRef:
    name: cluster-configs
 
  resources:
  - name: resource-group
    base:
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      spec:
        forProvider:
          location: ''
        providerConfigRef:
          name: azure-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.labels.resourcegroup
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.resourceGroupName

  - name: virtual-network
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: VirtualNetwork
      spec:
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          addressSpace:
          - 10.0.0.0/16
        providerConfigRef:
          name: azure-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-vnet"

  - name: subnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      spec:
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          virtualNetworkNameSelector:
            matchControllerRef: true
          addressPrefixes:
          - 10.0.0.0/19
        providerConfigRef:
          name: azure-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-subnet"

  - name: akscluster
    base:
      apiVersion: containerservice.azure.upbound.io/v1beta1
      kind: KubernetesCluster
      spec:
        forProvider:
          dnsPrefix: target-cluster-dns
          roleBasedAccessControlEnabled: true
          resourceGroupNameSelector:
            matchControllerRef: true
          defaultNodePool:
          - name: default
            nodeCount: ''
            vmSize: ''
            vnetSubnetIDSelector:
              matchControllerRef: true
          identity:
          - type: SystemAssigned
        writeConnectionSecretToRef:
          namespace: kube-system
        providerConfigRef:
          name: azure-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
    - fromFieldPath: metadata.name
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-akscluster"
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.kubernetesVersion
    - fromFieldPath: spec.parameters.nodeCount
      toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.clusterName
    # - type: ToCompositeFieldPath
    #   fromFieldPath: status.conditions[0].status
    #   toFieldPath: status.controlPlaneStatus
    connectionDetails:
    - fromConnectionSecretKey: kubeconfig
    readinessChecks:
    - type: MatchString
      fieldPath: status.conditions[0].status
      matchString: "True"

  # - name: aksnode
  #   base:
  #     apiVersion: containerservice.azure.upbound.io/v1beta1
  #     kind: KubernetesClusterNodePool
  #     spec:
  #       forProvider:
  #         kubernetesClusterIdSelector:
  #           matchControllerRef: true
  #         vnetSubnetIDSelector:
  #           matchControllerRef: true
  #       providerConfigRef:
  #         name: azure-provider
  #   patches:
  #   - type: PatchSet
  #     patchSetName: metadata
  #   - fromFieldPath: spec.id
  #     toFieldPath: metadata.name
  #     transforms:
  #     - type: string
  #       string:
  #         fmt: "ng0%s"
  #   - fromFieldPath: spec.parameters.nodeCount
  #     toFieldPath: spec.forProvider.nodeCount
  #   - fromFieldPath: spec.parameters.nodeSize
  #     toFieldPath: spec.forProvider.vmSize
  #     transforms:
  #     - type: map
  #       map:
  #         small: Standard_D2s_v3
  #         medium: Standard_D4s_v3
  #         large: Standard_D8s_v3
  #   - type: ToCompositeFieldPath
  #     fromFieldPath: status.conditions[0].status
  #     toFieldPath: status.nodePoolStatus
  #   readinessChecks:
  #   - type: MatchString
  #     fieldPath: status.conditions[0].status
  #     matchString: "True"